using System.Collections.Generic;
using ColossalFramework.Globalization;

namespace AIImprove
{
    // "我想我們的介面，支援多國語言" (2026-08-15): both UI surfaces (AIImproveMod.OnSettingsUI's
    // Content Manager page and IngameUI's UnifiedUI panel) pull every label through here instead
    // of hardcoding text, so both stay in sync automatically. Picks a translation table based on
    // ColossalFramework.Globalization.LocaleManager.instance.language (the same locale code the
    // game's own UI uses, e.g. "en", "zh-tw", "zh-cn") and falls back to English for any language
    // or key this project hasn't translated yet - never throws, never shows a blank label.
    internal static class Localization
    {
        private const string DefaultLanguage = "en";

        private static readonly Dictionary<string, Dictionary<string, string>> Strings =
            new Dictionary<string, Dictionary<string, string>>
            {
                [DefaultLanguage] = new Dictionary<string, string>
                {
                    ["panel.title"] = "AI_Improve - Feature Toggles",
                    ["category.emergency.title"] = "Emergency vehicles",
                    ["category.emergency.desc"] =
                        "Response caps, idle vehicles seeking nearby fires. Some dispatch logic uses " +
                        "an IL transpiler and is unaffected by this toggle.",
                    ["category.metro.title"] = "Metro",
                    ["category.metro.desc"] = "Platform assignment, mid-route rerouting.",
                    ["category.intercityTrain.title"] = "Intercity trains",
                    ["category.intercityTrain.desc"] =
                        "Platform assignment, mid-route rerouting, inbound spawn throttling.",
                    ["category.aircraft.title"] = "Aircraft & airports",
                    ["category.aircraft.desc"] =
                        "Gate assignment, mid-route rerouting, thunderstorm landing refusal.",
                    ["category.buses.title"] = "Local buses & passenger helicopters",
                    ["category.buses.desc"] = "Mid-route rerouting, boarding point assignment, capacity.",
                    ["category.intercityBus.title"] = "Intercity buses",
                    ["category.intercityBus.desc"] = "Mid-route rerouting threshold adjustment.",
                    ["category.traffic.title"] = "Ordinary city traffic",
                    ["category.traffic.desc"] = "Dynamic rerouting for private cars/taxis/trucks.",
                    ["category.citizens.title"] = "Citizens",
                    ["category.citizens.desc"] = "Adjusts driving/taxi probability based on congestion.",
                    ["category.racecars.title"] = "Race cars",
                    ["category.racecars.desc"] = "Speed cap, racetrack attractiveness.",
                    ["toggle.enable"] = "Enable",
                    ["toggle.on"] = "[On] ",
                    ["toggle.off"] = "[Off] ",
                    ["button.scanTrain"] = "Scan for empty intercity trains",
                    ["button.scanBus"] = "Scan for empty intercity buses",
                    ["category.intercityTrain.short"] = "intercity trains",
                    ["category.intercityBus.short"] = "intercity buses",
                    ["scan.noneFound"] = "No empty {0} found.",
                    ["scan.confirm"] =
                        "Found {0} empty {1} chain(s) ({2} vehicle instance(s) total, including trailers).\n\n" +
                        "Delete these vehicles now?",
                    ["uui.tooltip"] = "AI_Improve Settings",
                    ["header.status"] = "Active",
                    ["header.changelog"] = "Changelog",
                    ["tab.toggles"] = "Toggles",
                    ["tab.tuning"] = "Tuning",
                    ["tab.about"] = "About",
                    ["about.version"] = "Updated {0}",
                    ["about.github"] = "GitHub Source",
                    ["about.wiki"] = "Documentation Wiki",
                    ["about.workshop"] = "Steam Workshop Page",
                    ["about.reportIssue"] = "Report an Issue (GitHub)",
                    ["tune.fireResponders"] = "Max fire responders per building",
                    ["tune.lowRidership"] = "Intercity train low-ridership skip threshold",
                    ["tune.verboseLogging"] = "Verbose logging (only for bug reports - slows the game)",
                    ["nav.general"] = "General",
                    ["nav.transport"] = "Transport",
                    ["nav.emergency"] = "Emergency",
                    ["nav.citizens"] = "Citizens & Races",
                    ["subtab.settings"] = "Settings",
                    ["subtab.toggles"] = "Toggles",
                    ["subtab.tuning"] = "Tuning",
                    ["subtab.links"] = "Links",
                    ["nav.metro"] = "Metro",
                    ["nav.intercityTrain"] = "Intercity Trains",
                    ["nav.aircraft"] = "Aircraft",
                    ["nav.localTransport"] = "Local Transport",
                    ["nav.intercityBus"] = "Intercity Buses",
                    ["nav.citizensRaces"] = "Citizens & Races",
                    ["nav.citizenAI"] = "Citizen Transport AI",
                    ["nav.advanced"] = "Advanced",
                    ["feature.fireResponseCap"] = "Per-building responder cap",
                    ["feature.fireResponseCap.desc"] = "Caps how many fire trucks/helicopters respond to one burning building.",
                    ["feature.fireIdleSeek"] = "Idle vehicles seek nearby fires",
                    ["feature.fireIdleSeek.desc"] = "Idle/returning fire vehicles check for a nearby still-burning building first.",
                    ["feature.helicopterWeatherHalt"] = "Ground helicopters in storms",
                    ["feature.helicopterWeatherHalt.desc"] = "Emergency helicopters stay grounded during a thunderstorm.",
                    ["feature.metroPlatform"] = "Platform assignment",
                    ["feature.metroPlatform.desc"] = "Occupancy-aware metro platform assignment.",
                    ["feature.metroReroute"] = "Mid-route rerouting",
                    ["feature.metroReroute.desc"] = "Metro trains reroute around real-time congestion.",
                    ["feature.trainPlatform"] = "Platform assignment",
                    ["feature.trainPlatform.desc"] = "Occupancy-aware intercity train platform assignment.",
                    ["feature.trainReroute"] = "Mid-route rerouting",
                    ["feature.trainReroute.desc"] = "Intercity trains reroute around real-time congestion.",
                    ["feature.trainSpawnThrottle"] = "Inbound spawn throttling",
                    ["feature.trainSpawnThrottle.desc"] = "Throttles new intercity trains when the destination is saturated or ridership is low.",
                    ["feature.singleTrackDetector"] = "Single-track conflict detector",
                    ["feature.singleTrackDetector.desc"] = "Detect-and-log only - never changes train behaviour.",
                    ["feature.aircraftGate"] = "Gate assignment",
                    ["feature.aircraftGate.desc"] = "Occupancy-aware airport gate assignment.",
                    ["feature.aircraftReroute"] = "Mid-route rerouting",
                    ["feature.aircraftReroute.desc"] = "Aircraft reroute around real-time congestion while taxiing.",
                    ["feature.aircraftThunderstorm"] = "Thunderstorm landing refusal",
                    ["feature.aircraftThunderstorm.desc"] = "Airports refuse landings and departures during a thunderstorm.",
                    ["feature.localBusReroute"] = "Local bus rerouting",
                    ["feature.localBusReroute.desc"] = "Local city buses reroute around real-time congestion.",
                    ["feature.trafficReroute"] = "Ordinary traffic rerouting",
                    ["feature.trafficReroute.desc"] = "Private cars/taxis/trucks reroute around real-time congestion.",
                    ["feature.helicopterGate"] = "Passenger helicopter gate assignment",
                    ["feature.helicopterGate.desc"] = "Occupancy-aware landing-point assignment for passenger helicopters.",
                    ["feature.helicopterReroute"] = "Passenger helicopter rerouting",
                    ["feature.helicopterReroute.desc"] = "Passenger helicopters reroute around real-time congestion.",
                    ["feature.helicopterCapacity"] = "Passenger helicopter capacity boost",
                    ["feature.helicopterCapacity.desc"] = "Increases passenger helicopter capacity.",
                    ["feature.intercityBusReroute"] = "Intercity bus rerouting",
                    ["feature.intercityBusReroute.desc"] = "Intercity buses reroute around real-time congestion.",
                    ["feature.citizenCar"] = "Congestion-aware driving",
                    ["feature.citizenCar.desc"] = "Citizens are less likely to drive toward an already-congested destination.",
                    ["feature.citizenTaxi"] = "Boosted taxi usage",
                    ["feature.citizenTaxi.desc"] = "Increases taxi usage as an alternative to driving.",
                    ["feature.raceAttractiveness"] = "Racetrack attractiveness boost",
                    ["feature.raceAttractiveness.desc"] = "Increases the tourism draw of the motorsport race complex.",
                    ["feature.citizenTransportMode"] = "Custom transport mode weights",
                    ["feature.citizenTransportMode.desc"] = "Replaces vanilla's own car/taxi/bike odds with 4 weights you control: Walk, Drive, Taxi, Transit. Bypasses the citizen car/taxi probability toggles above while on.",
                    ["tune.fireUncapMinutes"] = "Minutes burning before cap lifts",
                    ["tune.rerouteDensity"] = "Reroute density threshold",
                    ["tune.stationSaturation"] = "Station saturation threshold",
                    ["tune.platformCandidates"] = "Platform candidates searched",
                    ["tune.lowRidershipSkipChance"] = "Low-ridership skip chance (%)",
                    ["tune.gateCandidates"] = "Gate candidates searched",
                    ["tune.perGateCapacity"] = "Aircraft per gate",
                    ["tune.helicopterCapacity"] = "Helicopter capacity (%)",
                    ["tune.citizenCarDensity"] = "Congestion threshold",
                    ["tune.citizenCarReduction"] = "Max probability reduction (%)",
                    ["tune.taxiMultiplier"] = "Taxi probability multiplier (%)",
                    ["tune.taxiFlatBonus"] = "Taxi probability flat bonus",
                    ["tune.raceAttractiveness"] = "Attractiveness multiplier (%)",
                    ["tune.citizenWalkWeight"] = "Walk weight",
                    ["tune.citizenDriveWeight"] = "Drive weight",
                    ["tune.citizenTaxiWeight"] = "Taxi weight",
                    ["tune.citizenTransitWeight"] = "Transit weight",
                    ["preset.balanced"] = "Balanced",
                    ["preset.transitOriented"] = "Transit-oriented",
                    ["preset.carDependent"] = "Car-dependent",
                    ["preset.walkable"] = "Walkable city",
                    ["tune.rerouteCooldown"] = "Reroute cooldown (seconds)",
                    ["tune.checkInterval"] = "Check interval (frames)",
                    ["lang.label"] = "Language",
                },
                ["zh-tw"] = new Dictionary<string, string>
                {
                    ["panel.title"] = "AI_Improve - 功能分類開關",
                    ["category.emergency.title"] = "緊急車輛 (Emergency vehicles)",
                    ["category.emergency.desc"] = "出勤上限、閒置車輛找附近火場。部分派遣邏輯用 IL 轉譯器實作，此開關對那部分無效",
                    ["category.metro.title"] = "地鐵 (Metro)",
                    ["category.metro.desc"] = "月台分配、中途改道",
                    ["category.intercityTrain.title"] = "城際火車 (Intercity trains)",
                    ["category.intercityTrain.desc"] = "月台分配、中途改道、入城流量節流",
                    ["category.aircraft.title"] = "飛機與機場 (Aircraft & airports)",
                    ["category.aircraft.desc"] = "登機門分配、中途改道、雷暴雨拒絕起降",
                    ["category.buses.title"] = "市內巴士與客運直升機 (Local buses & passenger helicopters)",
                    ["category.buses.desc"] = "中途改道、登機點分配、載客量",
                    ["category.intercityBus.title"] = "城際巴士 (Intercity buses)",
                    ["category.intercityBus.desc"] = "中途改道閾值調整",
                    ["category.traffic.title"] = "一般市內交通 (Ordinary city traffic)",
                    ["category.traffic.desc"] = "私家車/計程車/貨車動態改道",
                    ["category.citizens.title"] = "市民行為 (Citizens)",
                    ["category.citizens.desc"] = "依壅塞調整開車/計程車機率",
                    ["category.racecars.title"] = "賽車 (Race cars)",
                    ["category.racecars.desc"] = "速度上限、賽車場吸引力",
                    ["toggle.enable"] = "啟用此功能 (Enable)",
                    ["toggle.on"] = "[開] ",
                    ["toggle.off"] = "[關] ",
                    ["button.scanTrain"] = "檢測沒有乘客的城際火車",
                    ["button.scanBus"] = "檢測沒有乘客的城際巴士",
                    ["category.intercityTrain.short"] = "城際火車 (intercity trains)",
                    ["category.intercityBus.short"] = "城際巴士 (intercity buses)",
                    ["scan.noneFound"] = "沒有偵測到沒有乘客的{0}。",
                    ["scan.confirm"] = "偵測到 {0} 輛沒有乘客的{1}（共 {2} 節車廂/車輛實例）。\n\n是否要直接刪除這些車輛？",
                    ["uui.tooltip"] = "AI_Improve 設定 (Settings)",
                    ["header.status"] = "運作中 (Active)",
                    ["header.changelog"] = "更新日誌 (Changelog)",
                    ["tab.toggles"] = "功能開關",
                    ["tab.tuning"] = "數值調整",
                    ["tab.about"] = "關於",
                    ["about.version"] = "最後更新 (Updated) {0}",
                    ["about.github"] = "GitHub 原始碼",
                    ["about.wiki"] = "說明 Wiki",
                    ["about.workshop"] = "Steam Workshop 頁面",
                    ["about.reportIssue"] = "回報問題 (GitHub Issues)",
                    ["tune.fireResponders"] = "消防車/直升機每棟建築派遣上限",
                    ["tune.lowRidership"] = "城際火車低載客量跳過閾值",
                    ["tune.verboseLogging"] = "詳細記錄 (只在回報問題時開啟，會拖慢遊戲)",
                    ["nav.general"] = "一般",
                    ["nav.transport"] = "交通運輸",
                    ["nav.emergency"] = "緊急服務",
                    ["nav.citizens"] = "市民與賽車",
                    ["subtab.settings"] = "設定",
                    ["subtab.toggles"] = "功能開關",
                    ["subtab.tuning"] = "數值調整",
                    ["subtab.links"] = "相關連結",
                    ["nav.metro"] = "地鐵",
                    ["nav.intercityTrain"] = "城際火車",
                    ["nav.aircraft"] = "飛機與機場",
                    ["nav.localTransport"] = "市內交通",
                    ["nav.intercityBus"] = "城際巴士",
                    ["nav.citizensRaces"] = "市民與賽車",
                    ["nav.citizenAI"] = "市民交通 AI",
                    ["nav.advanced"] = "進階",
                    ["feature.fireResponseCap"] = "每棟建築派遣上限",
                    ["feature.fireResponseCap.desc"] = "限制單一起火建築最多可派遣多少消防車/直升機。",
                    ["feature.fireIdleSeek"] = "閒置車輛尋找附近火場",
                    ["feature.fireIdleSeek.desc"] = "閒置/返程中的消防車輛會優先檢查附近是否還有火場。",
                    ["feature.helicopterWeatherHalt"] = "雷暴雨時停飛直升機",
                    ["feature.helicopterWeatherHalt.desc"] = "雷暴雨期間緊急直升機停留在地面。",
                    ["feature.metroPlatform"] = "月台分配",
                    ["feature.metroPlatform.desc"] = "依佔用情況分配地鐵月台。",
                    ["feature.metroReroute"] = "中途改道",
                    ["feature.metroReroute.desc"] = "地鐵依即時壅塞情況改道。",
                    ["feature.trainPlatform"] = "月台分配",
                    ["feature.trainPlatform.desc"] = "依佔用情況分配城際火車月台。",
                    ["feature.trainReroute"] = "中途改道",
                    ["feature.trainReroute.desc"] = "城際火車依即時壅塞情況改道。",
                    ["feature.trainSpawnThrottle"] = "入城流量節流",
                    ["feature.trainSpawnThrottle.desc"] = "當目的地飽和或載客量偏低時，節流新生成的城際火車。",
                    ["feature.singleTrackDetector"] = "單線軌道衝突偵測",
                    ["feature.singleTrackDetector.desc"] = "只偵測並記錄，不會改變任何列車行為。",
                    ["feature.aircraftGate"] = "登機門分配",
                    ["feature.aircraftGate.desc"] = "依佔用情況分配機場登機門。",
                    ["feature.aircraftReroute"] = "中途改道",
                    ["feature.aircraftReroute.desc"] = "飛機滑行時依即時壅塞情況改道。",
                    ["feature.aircraftThunderstorm"] = "雷暴雨拒絕起降",
                    ["feature.aircraftThunderstorm.desc"] = "雷暴雨期間機場拒絕起降。",
                    ["feature.localBusReroute"] = "市內巴士改道",
                    ["feature.localBusReroute.desc"] = "市內巴士依即時壅塞情況改道。",
                    ["feature.trafficReroute"] = "一般交通改道",
                    ["feature.trafficReroute.desc"] = "私家車/計程車/貨車依即時壅塞情況改道。",
                    ["feature.helicopterGate"] = "客運直升機登機點分配",
                    ["feature.helicopterGate.desc"] = "依佔用情況分配客運直升機登機點。",
                    ["feature.helicopterReroute"] = "客運直升機改道",
                    ["feature.helicopterReroute.desc"] = "客運直升機依即時壅塞情況改道。",
                    ["feature.helicopterCapacity"] = "客運直升機載客量提升",
                    ["feature.helicopterCapacity.desc"] = "提升客運直升機載客量。",
                    ["feature.intercityBusReroute"] = "城際巴士改道",
                    ["feature.intercityBusReroute.desc"] = "城際巴士依即時壅塞情況改道。",
                    ["feature.citizenCar"] = "依壅塞調整開車機率",
                    ["feature.citizenCar.desc"] = "市民較不傾向開車前往已壅塞的目的地。",
                    ["feature.citizenTaxi"] = "提升計程車使用率",
                    ["feature.citizenTaxi.desc"] = "提升計程車作為開車的替代選項。",
                    ["feature.raceAttractiveness"] = "賽車場吸引力提升",
                    ["feature.raceAttractiveness.desc"] = "提升賽車場複合設施的觀光吸引力。",
                    ["feature.citizenTransportMode"] = "自訂交通方式權重",
                    ["feature.citizenTransportMode.desc"] = "取代原版的開車/的士/腳踏車機率，改用 4 個你自訂的權重：步行、開車、的士、大眾運輸。開啟時會略過上方的市民開車/的士機率開關。",
                    ["tune.fireUncapMinutes"] = "燃燒幾分鐘後解除上限",
                    ["tune.rerouteDensity"] = "改道壅塞閾值",
                    ["tune.stationSaturation"] = "車站飽和閾值",
                    ["tune.platformCandidates"] = "月台搜尋候選數",
                    ["tune.lowRidershipSkipChance"] = "低載客量跳過機率 (%)",
                    ["tune.gateCandidates"] = "登機門搜尋候選數",
                    ["tune.perGateCapacity"] = "每個登機門可容納飛機數",
                    ["tune.helicopterCapacity"] = "直升機載客量 (%)",
                    ["tune.citizenCarDensity"] = "壅塞判定閾值",
                    ["tune.citizenCarReduction"] = "最大機率降幅 (%)",
                    ["tune.taxiMultiplier"] = "計程車機率倍率 (%)",
                    ["tune.taxiFlatBonus"] = "計程車機率固定加成",
                    ["tune.raceAttractiveness"] = "吸引力倍率 (%)",
                    ["tune.citizenWalkWeight"] = "步行權重",
                    ["tune.citizenDriveWeight"] = "開車權重",
                    ["tune.citizenTaxiWeight"] = "的士權重",
                    ["tune.citizenTransitWeight"] = "大眾運輸權重",
                    ["preset.balanced"] = "均衡",
                    ["preset.transitOriented"] = "大眾運輸導向",
                    ["preset.carDependent"] = "汽車導向",
                    ["preset.walkable"] = "步行城市",
                    ["tune.rerouteCooldown"] = "改道冷卻時間（秒）",
                    ["tune.checkInterval"] = "檢查間隔（幀數）",
                    ["lang.label"] = "語言 (Language)",
                },
                ["zh-cn"] = new Dictionary<string, string>
                {
                    ["panel.title"] = "AI_Improve - 功能分类开关",
                    ["category.emergency.title"] = "紧急车辆 (Emergency vehicles)",
                    ["category.emergency.desc"] = "出勤上限、闲置车辆寻找附近火场。部分派遣逻辑用 IL 转译器实现，此开关对那部分无效",
                    ["category.metro.title"] = "地铁 (Metro)",
                    ["category.metro.desc"] = "月台分配、中途改道",
                    ["category.intercityTrain.title"] = "城际火车 (Intercity trains)",
                    ["category.intercityTrain.desc"] = "月台分配、中途改道、入城流量节流",
                    ["category.aircraft.title"] = "飞机与机场 (Aircraft & airports)",
                    ["category.aircraft.desc"] = "登机门分配、中途改道、雷暴雨拒绝起降",
                    ["category.buses.title"] = "市内巴士与客运直升机 (Local buses & passenger helicopters)",
                    ["category.buses.desc"] = "中途改道、登机点分配、载客量",
                    ["category.intercityBus.title"] = "城际巴士 (Intercity buses)",
                    ["category.intercityBus.desc"] = "中途改道阈值调整",
                    ["category.traffic.title"] = "一般市内交通 (Ordinary city traffic)",
                    ["category.traffic.desc"] = "私家车/出租车/货车动态改道",
                    ["category.citizens.title"] = "市民行为 (Citizens)",
                    ["category.citizens.desc"] = "依拥堵调整开车/出租车概率",
                    ["category.racecars.title"] = "赛车 (Race cars)",
                    ["category.racecars.desc"] = "速度上限、赛车场吸引力",
                    ["toggle.enable"] = "启用此功能 (Enable)",
                    ["toggle.on"] = "[开] ",
                    ["toggle.off"] = "[关] ",
                    ["button.scanTrain"] = "检测没有乘客的城际火车",
                    ["button.scanBus"] = "检测没有乘客的城际巴士",
                    ["category.intercityTrain.short"] = "城际火车 (intercity trains)",
                    ["category.intercityBus.short"] = "城际巴士 (intercity buses)",
                    ["scan.noneFound"] = "没有侦测到没有乘客的{0}。",
                    ["scan.confirm"] = "侦测到 {0} 辆没有乘客的{1}（共 {2} 节车厢/车辆实例）。\n\n是否要直接删除这些车辆？",
                    ["uui.tooltip"] = "AI_Improve 设定 (Settings)",
                    ["header.status"] = "运作中 (Active)",
                    ["header.changelog"] = "更新日志 (Changelog)",
                    ["tab.toggles"] = "功能开关",
                    ["tab.tuning"] = "数值调整",
                    ["tab.about"] = "关于",
                    ["about.version"] = "最后更新 (Updated) {0}",
                    ["about.github"] = "GitHub 源代码",
                    ["about.wiki"] = "说明 Wiki",
                    ["about.workshop"] = "Steam Workshop 页面",
                    ["about.reportIssue"] = "报告问题 (GitHub Issues)",
                    ["tune.fireResponders"] = "消防车/直升机每栋建筑派遣上限",
                    ["tune.lowRidership"] = "城际火车低载客量跳过阈值",
                    ["tune.verboseLogging"] = "详细记录 (只在报告问题时开启，会拖慢游戏)",
                    ["nav.general"] = "一般",
                    ["nav.transport"] = "交通运输",
                    ["nav.emergency"] = "紧急服务",
                    ["nav.citizens"] = "市民与赛车",
                    ["subtab.settings"] = "设置",
                    ["subtab.toggles"] = "功能开关",
                    ["subtab.tuning"] = "数值调整",
                    ["subtab.links"] = "相关链接",
                    ["nav.metro"] = "地铁",
                    ["nav.intercityTrain"] = "城际火车",
                    ["nav.aircraft"] = "飞机与机场",
                    ["nav.localTransport"] = "市内交通",
                    ["nav.intercityBus"] = "城际巴士",
                    ["nav.citizensRaces"] = "市民与赛车",
                    ["nav.citizenAI"] = "市民交通 AI",
                    ["nav.advanced"] = "进阶",
                    ["feature.fireResponseCap"] = "每栋建筑派遣上限",
                    ["feature.fireResponseCap.desc"] = "限制单一起火建筑最多可派遣多少消防车/直升机。",
                    ["feature.fireIdleSeek"] = "闲置车辆寻找附近火场",
                    ["feature.fireIdleSeek.desc"] = "闲置/返程中的消防车辆会优先检查附近是否还有火场。",
                    ["feature.helicopterWeatherHalt"] = "雷暴雨时停飞直升机",
                    ["feature.helicopterWeatherHalt.desc"] = "雷暴雨期间紧急直升机停留在地面。",
                    ["feature.metroPlatform"] = "站台分配",
                    ["feature.metroPlatform.desc"] = "依占用情况分配地铁站台。",
                    ["feature.metroReroute"] = "中途改道",
                    ["feature.metroReroute.desc"] = "地铁依实时拥堵情况改道。",
                    ["feature.trainPlatform"] = "站台分配",
                    ["feature.trainPlatform.desc"] = "依占用情况分配城际火车站台。",
                    ["feature.trainReroute"] = "中途改道",
                    ["feature.trainReroute.desc"] = "城际火车依实时拥堵情况改道。",
                    ["feature.trainSpawnThrottle"] = "入城流量节流",
                    ["feature.trainSpawnThrottle.desc"] = "当目的地饱和或载客量偏低时，节流新生成的城际火车。",
                    ["feature.singleTrackDetector"] = "单线轨道冲突侦测",
                    ["feature.singleTrackDetector.desc"] = "只侦测并记录，不会改变任何列车行为。",
                    ["feature.aircraftGate"] = "登机口分配",
                    ["feature.aircraftGate.desc"] = "依占用情况分配机场登机口。",
                    ["feature.aircraftReroute"] = "中途改道",
                    ["feature.aircraftReroute.desc"] = "飞机滑行时依实时拥堵情况改道。",
                    ["feature.aircraftThunderstorm"] = "雷暴雨拒绝起降",
                    ["feature.aircraftThunderstorm.desc"] = "雷暴雨期间机场拒绝起降。",
                    ["feature.localBusReroute"] = "市内巴士改道",
                    ["feature.localBusReroute.desc"] = "市内巴士依实时拥堵情况改道。",
                    ["feature.trafficReroute"] = "一般交通改道",
                    ["feature.trafficReroute.desc"] = "私家车/出租车/货车依实时拥堵情况改道。",
                    ["feature.helicopterGate"] = "客运直升机登机点分配",
                    ["feature.helicopterGate.desc"] = "依占用情况分配客运直升机登机点。",
                    ["feature.helicopterReroute"] = "客运直升机改道",
                    ["feature.helicopterReroute.desc"] = "客运直升机依实时拥堵情况改道。",
                    ["feature.helicopterCapacity"] = "客运直升机载客量提升",
                    ["feature.helicopterCapacity.desc"] = "提升客运直升机载客量。",
                    ["feature.intercityBusReroute"] = "城际巴士改道",
                    ["feature.intercityBusReroute.desc"] = "城际巴士依实时拥堵情况改道。",
                    ["feature.citizenCar"] = "依拥堵调整开车概率",
                    ["feature.citizenCar.desc"] = "市民较不倾向开车前往已拥堵的目的地。",
                    ["feature.citizenTaxi"] = "提升出租车使用率",
                    ["feature.citizenTaxi.desc"] = "提升出租车作为开车的替代选项。",
                    ["feature.raceAttractiveness"] = "赛车场吸引力提升",
                    ["feature.raceAttractiveness.desc"] = "提升赛车场综合设施的观光吸引力。",
                    ["feature.citizenTransportMode"] = "自定义交通方式权重",
                    ["feature.citizenTransportMode.desc"] = "取代原版的开车/出租车/自行车概率，改用 4 个你自定义的权重：步行、开车、出租车、大众运输。开启时会跳过上方的市民开车/出租车概率开关。",
                    ["tune.fireUncapMinutes"] = "燃烧几分钟后解除上限",
                    ["tune.rerouteDensity"] = "改道拥堵阈值",
                    ["tune.stationSaturation"] = "车站饱和阈值",
                    ["tune.platformCandidates"] = "站台搜索候选数",
                    ["tune.lowRidershipSkipChance"] = "低载客量跳过概率 (%)",
                    ["tune.gateCandidates"] = "登机口搜索候选数",
                    ["tune.perGateCapacity"] = "每个登机口可容纳飞机数",
                    ["tune.helicopterCapacity"] = "直升机载客量 (%)",
                    ["tune.citizenCarDensity"] = "拥堵判定阈值",
                    ["tune.citizenCarReduction"] = "最大概率降幅 (%)",
                    ["tune.taxiMultiplier"] = "出租车概率倍率 (%)",
                    ["tune.taxiFlatBonus"] = "出租车概率固定加成",
                    ["tune.raceAttractiveness"] = "吸引力倍率 (%)",
                    ["tune.citizenWalkWeight"] = "步行权重",
                    ["tune.citizenDriveWeight"] = "开车权重",
                    ["tune.citizenTaxiWeight"] = "出租车权重",
                    ["tune.citizenTransitWeight"] = "大众运输权重",
                    ["preset.balanced"] = "均衡",
                    ["preset.transitOriented"] = "大众运输导向",
                    ["preset.carDependent"] = "汽车导向",
                    ["preset.walkable"] = "步行城市",
                    ["tune.rerouteCooldown"] = "改道冷却时间（秒）",
                    ["tune.checkInterval"] = "检查间隔（帧数）",
                    ["lang.label"] = "语言 (Language)",
                },
            };

        public static string Get(string key)
        {
            string language = ResolveLanguage();

            if (Strings.TryGetValue(language, out Dictionary<string, string> table) &&
                table.TryGetValue(key, out string value))
            {
                return value;
            }

            return Strings[DefaultLanguage].TryGetValue(key, out string fallback) ? fallback : key;
        }

        public static string Get(string key, params object[] args) => string.Format(Get(key), args);

        // Every language code Localization actually has a translation table for - drives both
        // ResolveLanguage's override check and the language-cycle button in SettingsPageUI.cs, so
        // the two can't drift out of sync with each other.
        public static readonly string[] SupportedLanguages = { "en", "zh-tw", "zh-cn" };

        private static string ResolveLanguage()
        {
            string overrideLanguage = ModSettings.LanguageOverride.value;
            if (!string.IsNullOrEmpty(overrideLanguage) && overrideLanguage != "auto")
            {
                return overrideLanguage;
            }

            if (!LocaleManager.exists)
            {
                return DefaultLanguage;
            }

            string language = LocaleManager.instance.language;
            return string.IsNullOrEmpty(language) ? DefaultLanguage : language.ToLowerInvariant();
        }
    }
}
