using System.Collections.Generic;
using ColossalFramework.Globalization;

namespace AIImprove
{
    // "我想我們的介面，支援多國語言" (2026-08-15): both UI surfaces (AIImproveMod.OnSettingsUI's
    // Content Manager page and IngameUI's UnifiedUI panel) pull every label through here instead
    // of hardcoding text, so both stay in sync automatically. Picks a translation table based on
    // ColossalFramework.Globalization.LocaleManager.instance.language (the same locale code the
    // game's own UI uses, e.g. "en", "zh-tw", "zh-cn") and falls back to English for any language
    // or key this project hasn't translated yet - never throws, never shows a blank label.
    internal static class Localization
    {
        private const string DefaultLanguage = "en";

        private static readonly Dictionary<string, Dictionary<string, string>> Strings =
            new Dictionary<string, Dictionary<string, string>>
            {
                [DefaultLanguage] = new Dictionary<string, string>
                {
                    ["panel.title"] = "AI_Improve - Feature Toggles",
                    ["category.emergency.title"] = "Emergency vehicles",
                    ["category.emergency.desc"] =
                        "Response caps, idle vehicles seeking nearby fires. Some dispatch logic uses " +
                        "an IL transpiler and is unaffected by this toggle.",
                    ["category.metro.title"] = "Metro",
                    ["category.metro.desc"] = "Platform assignment, mid-route rerouting.",
                    ["category.intercityTrain.title"] = "Intercity trains",
                    ["category.intercityTrain.desc"] =
                        "Platform assignment, mid-route rerouting, inbound spawn throttling.",
                    ["category.aircraft.title"] = "Aircraft & airports",
                    ["category.aircraft.desc"] =
                        "Gate assignment, mid-route rerouting, thunderstorm landing refusal.",
                    ["category.buses.title"] = "Local buses & passenger helicopters",
                    ["category.buses.desc"] = "Mid-route rerouting, boarding point assignment, capacity.",
                    ["category.intercityBus.title"] = "Intercity buses",
                    ["category.intercityBus.desc"] = "Mid-route rerouting threshold adjustment.",
                    ["category.traffic.title"] = "Ordinary city traffic",
                    ["category.traffic.desc"] = "Dynamic rerouting for private cars/taxis/trucks.",
                    ["category.citizens.title"] = "Citizens",
                    ["category.citizens.desc"] = "Adjusts driving/taxi probability based on congestion.",
                    ["category.racecars.title"] = "Race cars",
                    ["category.racecars.desc"] = "Speed cap, racetrack attractiveness.",
                    ["toggle.enable"] = "Enable",
                    ["toggle.on"] = "[On] ",
                    ["toggle.off"] = "[Off] ",
                    ["button.scanTrain"] = "Scan for empty intercity trains",
                    ["button.scanBus"] = "Scan for empty intercity buses",
                    ["category.intercityTrain.short"] = "intercity trains",
                    ["category.intercityBus.short"] = "intercity buses",
                    ["scan.noneFound"] = "No empty {0} found.",
                    ["scan.confirm"] =
                        "Found {0} empty {1} chain(s) ({2} vehicle instance(s) total, including trailers).\n\n" +
                        "Delete these vehicles now?",
                    ["uui.tooltip"] = "AI_Improve Settings",
                    ["header.status"] = "Active",
                    ["header.changelog"] = "Changelog",
                    ["header.search"] = "Search settings",
                    ["header.reset"] = "Reset to defaults",
                    ["header.reset.desc"] = "Restores every feature switch and every adjustable value to what a fresh install uses. Your language choice is left alone.",
                    ["header.reset.confirm"] = "Reset every AI_Improve setting back to its default value?\n\nThis affects all feature switches and all adjustable values. Your language choice is not changed.",
                    ["search.noResults"] = "Nothing matches \"{0}\". Clear the search box to go back to the section list.",
                    ["feature.rerouteTiming"] = "Reroute timing",
                    ["feature.rerouteTiming.desc"] = "Shared by every rerouting feature - these control how often vehicles reconsider their route, not whether they do.",
                    ["tab.toggles"] = "Toggles",
                    ["tab.tuning"] = "Tuning",
                    ["tab.about"] = "About",
                    ["about.version"] = "Updated {0}",
                    ["about.github"] = "GitHub Source",
                    ["about.wiki"] = "Documentation Wiki",
                    ["about.workshop"] = "Steam Workshop Page",
                    ["about.reportIssue"] = "Report an Issue (GitHub)",
                    ["tune.fireResponders"] = "Max fire responders per building",
                    ["tune.fireResponders.desc"] = "How many trucks/helicopters may respond to the same burning building before extras get redirected elsewhere.",
                    ["tune.lowRidership"] = "Intercity train low-ridership skip threshold",
                    ["tune.lowRidership.desc"] = "Below this many recent riders, an incoming intercity train spawn may be skipped instead of arriving empty. 0 disables this throttle entirely.",
                    ["tune.verboseLogging"] = "Verbose logging (only for bug reports - slows the game)",
                    ["tune.verboseLogging.desc"] = "Logs every individual dispatch/reroute/redirect decision, not just summaries. Only useful when reproducing a bug for a report - writes a lot to disk.",
                    // Section names, grouped by transport mode (2026-08-17 reorganisation - see
                    // SettingsPageUI.BuildModel). The old per-vehicle-type keys (nav.metro,
                    // nav.intercityTrain, nav.aircraft, nav.localTransport, nav.intercityBus,
                    // nav.cargo, nav.citizensRaces, nav.citizenAI) and the subtab.* keys from the
                    // retired tab strip are gone with the layout that used them.
                    ["nav.general"] = "General",
                    ["nav.citizens"] = "Citizens",
                    ["nav.emergency"] = "Emergency",
                    ["nav.road"] = "Road Traffic",
                    ["nav.rail"] = "Rail",
                    ["nav.aviation"] = "Aviation",
                    ["nav.shipping"] = "Shipping & Cargo",
                    ["nav.races"] = "Races",
                    ["nav.advanced"] = "Advanced",
                    ["feature.fireResponseCap"] = "Per-building responder cap",
                    ["feature.fireResponseCap.desc"] = "Caps how many fire trucks/helicopters respond to one burning building.",
                    ["feature.fireIdleSeek"] = "Idle vehicles seek nearby fires",
                    ["feature.fireIdleSeek.desc"] = "Idle/returning fire vehicles check for a nearby still-burning building first.",
                    ["feature.helicopterWeatherHalt"] = "Ground helicopters in storms",
                    ["feature.helicopterWeatherHalt.desc"] = "Emergency helicopters stay grounded during a thunderstorm.",
                    ["feature.metroPlatform"] = "Platform assignment",
                    ["feature.metroPlatform.desc"] = "Occupancy-aware metro platform assignment.",
                    ["feature.metroReroute"] = "Mid-route rerouting",
                    ["feature.metroReroute.desc"] = "Metro trains reroute around real-time congestion.",
                    ["feature.trainPlatform"] = "Platform assignment",
                    ["feature.trainPlatform.desc"] = "Occupancy-aware intercity train platform assignment.",
                    ["feature.trainReroute"] = "Mid-route rerouting",
                    ["feature.trainReroute.desc"] = "Intercity trains reroute around real-time congestion.",
                    ["feature.trainSpawnThrottle"] = "Inbound spawn throttling",
                    ["feature.trainSpawnThrottle.desc"] = "Throttles new intercity trains when the destination is saturated or ridership is low.",
                    ["feature.singleTrackDetector"] = "Single-track conflict detector",
                    ["feature.singleTrackDetector.desc"] = "Detect-and-log only - never changes train behaviour.",
                    ["feature.aircraftGate"] = "Gate assignment",
                    ["feature.aircraftGate.desc"] = "Occupancy-aware airport gate assignment.",
                    ["feature.aircraftReroute"] = "Mid-route rerouting",
                    ["feature.aircraftReroute.desc"] = "Aircraft reroute around real-time congestion while taxiing.",
                    ["feature.aircraftThunderstorm"] = "Thunderstorm landing refusal",
                    ["feature.aircraftThunderstorm.desc"] = "Airports refuse landings and departures during a thunderstorm.",
                    ["feature.localBusReroute"] = "Local bus rerouting",
                    ["feature.localBusReroute.desc"] = "Local city buses reroute around real-time congestion.",
                    ["feature.trafficReroute"] = "Ordinary traffic rerouting",
                    ["feature.trafficReroute.desc"] = "Private cars/taxis/trucks reroute around real-time congestion.",
                    ["feature.helicopterGate"] = "Passenger helicopter gate assignment",
                    ["feature.helicopterGate.desc"] = "Occupancy-aware landing-point assignment for passenger helicopters.",
                    ["feature.helicopterReroute"] = "Passenger helicopter rerouting",
                    ["feature.helicopterReroute.desc"] = "Passenger helicopters reroute around real-time congestion.",
                    ["feature.helicopterCapacity"] = "Passenger helicopter capacity boost",
                    ["feature.helicopterCapacity.desc"] = "Increases passenger helicopter capacity.",
                    ["feature.intercityBusReroute"] = "Intercity bus rerouting",
                    ["feature.intercityBusReroute.desc"] = "Intercity buses reroute around real-time congestion.",
                    ["feature.citizenCar"] = "Congestion-aware driving",
                    ["feature.citizenCar.desc"] = "Citizens are less likely to drive toward an already-congested destination.",
                    ["feature.citizenTaxi"] = "Boosted taxi usage",
                    ["feature.citizenTaxi.desc"] = "Increases taxi usage as an alternative to driving.",
                    ["feature.raceAttractiveness"] = "Racetrack attractiveness boost",
                    ["feature.raceAttractiveness.desc"] = "Increases the tourism draw of the motorsport race complex.",
                    ["feature.citizenTransportMode"] = "Custom transport mode weights",
                    ["feature.citizenTransportMode.desc"] = "Replaces vanilla's own car/taxi/bike odds with 4 weights you control: Walk, Drive, Taxi, Transit. Bypasses the citizen car/taxi probability toggles above while on.",
                    ["feature.shipDock"] = "Ship dock assignment",
                    ["feature.shipDock.desc"] = "Occupancy-aware dock assignment for cargo ships and passenger ferries - spreads traffic across a harbor's real dock capacity instead of vanilla's blind pathfind.",
                    ["tune.fireUncapMinutes"] = "Minutes burning before cap lifts",
                    ["tune.fireUncapMinutes.desc"] = "After a building has been burning this long, the responder cap stops applying to it - a long-running fire keeps getting help instead of staying stuck at the cap.",
                    ["tune.rerouteDensity"] = "Reroute density threshold",
                    ["tune.rerouteDensity.desc"] = "How congested the road/track/lane ahead has to be (0-100) before a vehicle mid-trip reroutes around it. Lower = reroutes more eagerly.",
                    // Rail-only now; the ship section has its own tune.harborSaturation, so this
                    // no longer has to hedge between "platform/dock" and "station/harbor".
                    ["tune.stationSaturation"] = "Station saturation threshold",
                    ["tune.stationSaturation.desc"] = "When the least-busy candidate platform is already at or above this occupancy, the station is treated as saturated and vanilla's own choice is left alone instead of forcing a still-crowded platform.",
                    ["tune.harborSaturation"] = "Harbor saturation threshold",
                    ["tune.harborSaturation.desc"] = "When the least-busy candidate dock is already at or above this occupancy, the harbor is treated as saturated and vanilla's own choice is left alone instead of forcing a still-crowded dock.",
                    ["tune.dockCandidates"] = "Dock candidates searched",
                    ["tune.dockCandidates.desc"] = "How many candidate points are probed around a harbor when spreading ships across its docks. Higher covers a bigger harbor more thoroughly but costs more to compute.",
                    ["tune.platformCandidates"] = "Platform candidates searched",
                    ["tune.platformCandidates.desc"] = "How many candidate points are probed around a station when spreading trains across its platforms. Higher covers a bigger station more thoroughly but costs more to compute.",
                    ["tune.lowRidershipSkipChance"] = "Low-ridership skip chance (%)",
                    ["tune.lowRidershipSkipChance.desc"] = "When a station is below the low-ridership threshold, this is the percent chance an incoming train spawn is skipped rather than arriving nearly empty.",
                    ["tune.gateCandidates"] = "Gate candidates searched",
                    ["tune.gateCandidates.desc"] = "How many candidate points are probed around an airport when spreading aircraft across its gates. Higher covers a bigger airport more thoroughly but costs more to compute.",
                    ["tune.perGateCapacity"] = "Aircraft per gate",
                    ["tune.perGateCapacity.desc"] = "Roughly how many aircraft each real gate found at an airport can hold before the whole airport is judged saturated (scaled by how many gates were actually found there).",
                    ["tune.helicopterCapacity"] = "Helicopter capacity (%)",
                    ["tune.helicopterCapacity.desc"] = "Passenger helicopter seat capacity as a percent of the vehicle's base value (200 = double).",
                    ["tune.citizenCarDensity"] = "Congestion threshold",
                    ["tune.citizenCarDensity.desc"] = "How congested a destination has to be (0-100) before citizens start becoming less likely to drive there.",
                    ["tune.citizenCarReduction"] = "Max probability reduction (%)",
                    ["tune.citizenCarReduction.desc"] = "The largest share of a citizen's drive-probability that congestion is allowed to remove, even at maximum congestion.",
                    ["tune.taxiMultiplier"] = "Taxi probability multiplier (%)",
                    ["tune.taxiMultiplier.desc"] = "Multiplies citizens' base taxi-usage probability (150 = 1.5x).",
                    ["tune.taxiFlatBonus"] = "Taxi probability flat bonus",
                    ["tune.taxiFlatBonus.desc"] = "A flat percentage-point bonus added on top of the multiplier above, so taxis stay a real option even where the base probability starts near zero.",
                    ["tune.raceAttractiveness"] = "Attractiveness multiplier (%)",
                    ["tune.raceAttractiveness.desc"] = "Tourism draw of the motorsport race complex as a percent of its base value (200 = double).",
                    ["tune.citizenWalkWeight"] = "Walk weight",
                    ["tune.citizenWalkWeight.desc"] = "Relative weight for walking the whole trip. 0 = no citizen ever walks-only; higher = more do. Weighed against the other 3 below, not an absolute percentage.",
                    ["tune.citizenDriveWeight"] = "Drive weight",
                    ["tune.citizenDriveWeight.desc"] = "Relative weight for driving a private car. Weighed against the other 3 weights, not an absolute percentage.",
                    ["tune.citizenTaxiWeight"] = "Taxi weight",
                    ["tune.citizenTaxiWeight.desc"] = "Relative weight for taking a taxi. Weighed against the other 3 weights, not an absolute percentage.",
                    ["tune.citizenTransitWeight"] = "Transit weight",
                    ["tune.citizenTransitWeight.desc"] = "Relative weight for allowing public transport (bus/metro/train/other combined - vanilla has no way to pick one specific type). Not a hard guarantee: reaching a stop still requires some walking.",
                    ["preset.label"] = "Quick presets",
                    ["preset.balanced"] = "Balanced",
                    ["preset.transitOriented"] = "Transit-oriented",
                    ["preset.carDependent"] = "Car-dependent",
                    ["preset.walkable"] = "Walkable city",
                    ["tune.rerouteCooldown"] = "Reroute cooldown (seconds)",
                    ["tune.rerouteCooldown.desc"] = "Minimum time a vehicle must wait after rerouting before it's allowed to reroute again, so it doesn't flip-flop between routes.",
                    ["tune.checkInterval"] = "Check interval (frames)",
                    ["tune.checkInterval.desc"] = "How often (in simulation frames) each vehicle's congestion is re-checked. Higher spreads the cost across more frames but reacts to new congestion more slowly.",
                    ["lang.label"] = "Language",
                },
                ["zh-tw"] = new Dictionary<string, string>
                {
                    ["panel.title"] = "AI_Improve - 功能分類開關",
                    ["category.emergency.title"] = "緊急車輛 (Emergency vehicles)",
                    ["category.emergency.desc"] = "出勤上限、閒置車輛找附近火場。部分派遣邏輯用 IL 轉譯器實作，此開關對那部分無效",
                    ["category.metro.title"] = "地鐵 (Metro)",
                    ["category.metro.desc"] = "月台分配、中途改道",
                    ["category.intercityTrain.title"] = "城際火車 (Intercity trains)",
                    ["category.intercityTrain.desc"] = "月台分配、中途改道、入城流量節流",
                    ["category.aircraft.title"] = "飛機與機場 (Aircraft & airports)",
                    ["category.aircraft.desc"] = "登機門分配、中途改道、雷暴雨拒絕起降",
                    ["category.buses.title"] = "市內巴士與客運直升機 (Local buses & passenger helicopters)",
                    ["category.buses.desc"] = "中途改道、登機點分配、載客量",
                    ["category.intercityBus.title"] = "城際巴士 (Intercity buses)",
                    ["category.intercityBus.desc"] = "中途改道閾值調整",
                    ["category.traffic.title"] = "一般市內交通 (Ordinary city traffic)",
                    ["category.traffic.desc"] = "私家車/計程車/貨車動態改道",
                    ["category.citizens.title"] = "市民行為 (Citizens)",
                    ["category.citizens.desc"] = "依壅塞調整開車/計程車機率",
                    ["category.racecars.title"] = "賽車 (Race cars)",
                    ["category.racecars.desc"] = "速度上限、賽車場吸引力",
                    ["toggle.enable"] = "啟用此功能 (Enable)",
                    ["toggle.on"] = "[開] ",
                    ["toggle.off"] = "[關] ",
                    ["button.scanTrain"] = "檢測沒有乘客的城際火車",
                    ["button.scanBus"] = "檢測沒有乘客的城際巴士",
                    ["category.intercityTrain.short"] = "城際火車 (intercity trains)",
                    ["category.intercityBus.short"] = "城際巴士 (intercity buses)",
                    ["scan.noneFound"] = "沒有偵測到沒有乘客的{0}。",
                    ["scan.confirm"] = "偵測到 {0} 輛沒有乘客的{1}（共 {2} 節車廂/車輛實例）。\n\n是否要直接刪除這些車輛？",
                    ["uui.tooltip"] = "AI_Improve 設定 (Settings)",
                    ["header.status"] = "運作中 (Active)",
                    ["header.changelog"] = "更新日誌 (Changelog)",
                    ["header.search"] = "搜尋設定",
                    ["header.reset"] = "重設為預設值",
                    ["header.reset.desc"] = "把所有功能開關和所有可調整數值還原成全新安裝時的狀態。你選擇的語言不會被改動。",
                    ["header.reset.confirm"] = "要把 AI_Improve 的所有設定還原成預設值嗎？\n\n這會影響所有功能開關和所有可調整數值。你選擇的語言不會被改動。",
                    ["search.noResults"] = "找不到符合「{0}」的設定。清空搜尋框即可回到分頁列表。",
                    ["feature.rerouteTiming"] = "改道時機",
                    ["feature.rerouteTiming.desc"] = "所有改道功能共用的設定——這些控制的是車輛多常重新考慮路線，而不是要不要改道。",
                    ["tab.toggles"] = "功能開關",
                    ["tab.tuning"] = "數值調整",
                    ["tab.about"] = "關於",
                    ["about.version"] = "最後更新 (Updated) {0}",
                    ["about.github"] = "GitHub 原始碼",
                    ["about.wiki"] = "說明 Wiki",
                    ["about.workshop"] = "Steam Workshop 頁面",
                    ["about.reportIssue"] = "回報問題 (GitHub Issues)",
                    ["tune.fireResponders"] = "消防車/直升機每棟建築派遣上限",
                    ["tune.fireResponders.desc"] = "同一棟燃燒中的建築最多可以有幾台消防車/直升機同時前往，超過的會被改派到其他地方。",
                    ["tune.lowRidership"] = "城際火車低載客量跳過閾值",
                    ["tune.lowRidership.desc"] = "最近載客量低於這個人數時，可能會跳過一次即將進站的城際火車，而不是讓它幾乎空車進站。設為 0 會完全停用這個節流機制。",
                    ["tune.verboseLogging"] = "詳細記錄 (只在回報問題時開啟，會拖慢遊戲)",
                    ["tune.verboseLogging.desc"] = "記錄每一個派遣/改道/重新導向的細節，不只是摘要。只有在為了回報問題而重現時才需要開啟，會大量寫入硬碟。",
                    ["nav.general"] = "一般",
                    ["nav.citizens"] = "市民",
                    ["nav.emergency"] = "緊急服務",
                    ["nav.road"] = "道路交通",
                    ["nav.rail"] = "鐵路",
                    ["nav.aviation"] = "航空",
                    ["nav.shipping"] = "船運與貨運",
                    ["nav.races"] = "賽事",
                    ["nav.advanced"] = "進階",
                    ["feature.fireResponseCap"] = "每棟建築派遣上限",
                    ["feature.fireResponseCap.desc"] = "限制單一起火建築最多可派遣多少消防車/直升機。",
                    ["feature.fireIdleSeek"] = "閒置車輛尋找附近火場",
                    ["feature.fireIdleSeek.desc"] = "閒置/返程中的消防車輛會優先檢查附近是否還有火場。",
                    ["feature.helicopterWeatherHalt"] = "雷暴雨時停飛直升機",
                    ["feature.helicopterWeatherHalt.desc"] = "雷暴雨期間緊急直升機停留在地面。",
                    ["feature.metroPlatform"] = "月台分配",
                    ["feature.metroPlatform.desc"] = "依佔用情況分配地鐵月台。",
                    ["feature.metroReroute"] = "中途改道",
                    ["feature.metroReroute.desc"] = "地鐵依即時壅塞情況改道。",
                    ["feature.trainPlatform"] = "月台分配",
                    ["feature.trainPlatform.desc"] = "依佔用情況分配城際火車月台。",
                    ["feature.trainReroute"] = "中途改道",
                    ["feature.trainReroute.desc"] = "城際火車依即時壅塞情況改道。",
                    ["feature.trainSpawnThrottle"] = "入城流量節流",
                    ["feature.trainSpawnThrottle.desc"] = "當目的地飽和或載客量偏低時，節流新生成的城際火車。",
                    ["feature.singleTrackDetector"] = "單線軌道衝突偵測",
                    ["feature.singleTrackDetector.desc"] = "只偵測並記錄，不會改變任何列車行為。",
                    ["feature.aircraftGate"] = "登機門分配",
                    ["feature.aircraftGate.desc"] = "依佔用情況分配機場登機門。",
                    ["feature.aircraftReroute"] = "中途改道",
                    ["feature.aircraftReroute.desc"] = "飛機滑行時依即時壅塞情況改道。",
                    ["feature.aircraftThunderstorm"] = "雷暴雨拒絕起降",
                    ["feature.aircraftThunderstorm.desc"] = "雷暴雨期間機場拒絕起降。",
                    ["feature.localBusReroute"] = "市內巴士改道",
                    ["feature.localBusReroute.desc"] = "市內巴士依即時壅塞情況改道。",
                    ["feature.trafficReroute"] = "一般交通改道",
                    ["feature.trafficReroute.desc"] = "私家車/計程車/貨車依即時壅塞情況改道。",
                    ["feature.helicopterGate"] = "客運直升機登機點分配",
                    ["feature.helicopterGate.desc"] = "依佔用情況分配客運直升機登機點。",
                    ["feature.helicopterReroute"] = "客運直升機改道",
                    ["feature.helicopterReroute.desc"] = "客運直升機依即時壅塞情況改道。",
                    ["feature.helicopterCapacity"] = "客運直升機載客量提升",
                    ["feature.helicopterCapacity.desc"] = "提升客運直升機載客量。",
                    ["feature.intercityBusReroute"] = "城際巴士改道",
                    ["feature.intercityBusReroute.desc"] = "城際巴士依即時壅塞情況改道。",
                    ["feature.citizenCar"] = "依壅塞調整開車機率",
                    ["feature.citizenCar.desc"] = "市民較不傾向開車前往已壅塞的目的地。",
                    ["feature.citizenTaxi"] = "提升計程車使用率",
                    ["feature.citizenTaxi.desc"] = "提升計程車作為開車的替代選項。",
                    ["feature.raceAttractiveness"] = "賽車場吸引力提升",
                    ["feature.raceAttractiveness.desc"] = "提升賽車場複合設施的觀光吸引力。",
                    ["feature.citizenTransportMode"] = "自訂交通方式權重",
                    ["feature.citizenTransportMode.desc"] = "取代原版的開車/的士/腳踏車機率，改用 4 個你自訂的權重：步行、開車、的士、大眾運輸。開啟時會略過上方的市民開車/的士機率開關。",
                    ["feature.shipDock"] = "船運碼頭分配",
                    ["feature.shipDock.desc"] = "依佔用情況分配貨輪與客運渡輪的碼頭，把船運流量分散到港口真正的碼頭容量上，而不是擠在原版盲目挑中的同一個碼頭。",
                    ["tune.fireUncapMinutes"] = "燃燒幾分鐘後解除上限",
                    ["tune.fireUncapMinutes.desc"] = "一棟建築燃燒超過這麼久之後，派遣上限就不再套用在它身上——長時間的火災會持續獲得支援，不會卡在上限。",
                    ["tune.rerouteDensity"] = "改道壅塞閾值",
                    ["tune.rerouteDensity.desc"] = "前方道路/軌道/車道的壅塞度要達到多少（0-100）才會觸發車輛行駛途中改道。數值越低，改道越積極。",
                    ["tune.stationSaturation"] = "車站飽和閾值",
                    ["tune.stationSaturation.desc"] = "當佔用量最低的候選月台已經達到或超過這個值時，就視為該車站已飽和，改為保留原版自己的選擇，不強制塞進還很擁擠的月台。",
                    ["tune.harborSaturation"] = "港口飽和閾值",
                    ["tune.harborSaturation.desc"] = "當佔用量最低的候選碼頭已經達到或超過這個值時，就視為該港口已飽和，改為保留原版自己的選擇，不強制塞進還很擁擠的碼頭。",
                    ["tune.dockCandidates"] = "碼頭搜尋候選數",
                    ["tune.dockCandidates.desc"] = "在港口周圍探測幾個候選點來分散船隻到各碼頭。數字越大涵蓋範圍越完整，但運算量也越高。",
                    ["tune.platformCandidates"] = "月台搜尋候選數",
                    ["tune.platformCandidates.desc"] = "在車站周圍探測幾個候選點來分散火車到各月台。數字越大涵蓋範圍越完整，但運算量也越高。",
                    ["tune.lowRidershipSkipChance"] = "低載客量跳過機率 (%)",
                    ["tune.lowRidershipSkipChance.desc"] = "當車站低於低載客量閾值時，這是跳過一次進站火車而不是讓它幾乎空車抵達的機率百分比。",
                    ["tune.gateCandidates"] = "登機門搜尋候選數",
                    ["tune.gateCandidates.desc"] = "在機場周圍探測幾個候選點來分散飛機到各登機門。數字越大涵蓋範圍越完整，但運算量也越高。",
                    ["tune.perGateCapacity"] = "每個登機門可容納飛機數",
                    ["tune.perGateCapacity.desc"] = "機場找到的每個真實登機門大約可以容納多少架飛機，超過就視為整個機場飽和（會依實際找到的登機門數量按比例調整）。",
                    ["tune.helicopterCapacity"] = "直升機載客量 (%)",
                    ["tune.helicopterCapacity.desc"] = "客運直升機座位容量，以載具原本容量的百分比表示（200 = 兩倍）。",
                    ["tune.citizenCarDensity"] = "壅塞判定閾值",
                    ["tune.citizenCarDensity.desc"] = "目的地的壅塞度要達到多少（0-100）才會開始降低市民開車過去的機率。",
                    ["tune.citizenCarReduction"] = "最大機率降幅 (%)",
                    ["tune.citizenCarReduction.desc"] = "即使在最壅塞的情況下，壅塞最多可以降低市民開車機率的百分比上限。",
                    ["tune.taxiMultiplier"] = "計程車機率倍率 (%)",
                    ["tune.taxiMultiplier.desc"] = "把市民搭計程車的基礎機率乘上這個倍率（150 = 1.5 倍）。",
                    ["tune.taxiFlatBonus"] = "計程車機率固定加成",
                    ["tune.taxiFlatBonus.desc"] = "在上面的倍率之外再加上的固定百分點加成，讓計程車在基礎機率接近零的情況下仍然是個實際選項。",
                    ["tune.raceAttractiveness"] = "吸引力倍率 (%)",
                    ["tune.raceAttractiveness.desc"] = "賽車場複合設施的觀光吸引力，以原本數值的百分比表示（200 = 兩倍）。",
                    ["tune.citizenWalkWeight"] = "步行權重",
                    ["tune.citizenWalkWeight.desc"] = "整趟行程都用走的的相對權重。0 = 沒有市民會純步行；數值越高越多人走路。跟下面另外 3 個權重相比較，不是絕對百分比。",
                    ["tune.citizenDriveWeight"] = "開車權重",
                    ["tune.citizenDriveWeight.desc"] = "開私家車的相對權重。跟另外 3 個權重相比較，不是絕對百分比。",
                    ["tune.citizenTaxiWeight"] = "的士權重",
                    ["tune.citizenTaxiWeight.desc"] = "搭計程車的相對權重。跟另外 3 個權重相比較，不是絕對百分比。",
                    ["tune.citizenTransitWeight"] = "大眾運輸權重",
                    ["tune.citizenTransitWeight.desc"] = "允許搭乘大眾運輸的相對權重（巴士/地鐵/火車/其他合併計算——原版沒有辦法單獨指定某一種）。不是絕對保證：走到站牌仍然需要一些步行。",
                    ["preset.label"] = "快速套用模板",
                    ["preset.balanced"] = "均衡",
                    ["preset.transitOriented"] = "大眾運輸導向",
                    ["preset.carDependent"] = "汽車導向",
                    ["preset.walkable"] = "步行城市",
                    ["tune.rerouteCooldown"] = "改道冷卻時間（秒）",
                    ["tune.rerouteCooldown.desc"] = "車輛改道後，至少要等這麼久才能再次改道，避免在兩條路線之間來回猶豫。",
                    ["tune.checkInterval"] = "檢查間隔（幀數）",
                    ["tune.checkInterval.desc"] = "每隔幾個模擬幀數重新檢查一次每台車的壅塞狀況。數值越大，運算量分散得越開，但對新壅塞的反應也越慢。",
                    ["lang.label"] = "語言 (Language)",
                },
                ["zh-cn"] = new Dictionary<string, string>
                {
                    ["panel.title"] = "AI_Improve - 功能分类开关",
                    ["category.emergency.title"] = "紧急车辆 (Emergency vehicles)",
                    ["category.emergency.desc"] = "出勤上限、闲置车辆寻找附近火场。部分派遣逻辑用 IL 转译器实现，此开关对那部分无效",
                    ["category.metro.title"] = "地铁 (Metro)",
                    ["category.metro.desc"] = "月台分配、中途改道",
                    ["category.intercityTrain.title"] = "城际火车 (Intercity trains)",
                    ["category.intercityTrain.desc"] = "月台分配、中途改道、入城流量节流",
                    ["category.aircraft.title"] = "飞机与机场 (Aircraft & airports)",
                    ["category.aircraft.desc"] = "登机门分配、中途改道、雷暴雨拒绝起降",
                    ["category.buses.title"] = "市内巴士与客运直升机 (Local buses & passenger helicopters)",
                    ["category.buses.desc"] = "中途改道、登机点分配、载客量",
                    ["category.intercityBus.title"] = "城际巴士 (Intercity buses)",
                    ["category.intercityBus.desc"] = "中途改道阈值调整",
                    ["category.traffic.title"] = "一般市内交通 (Ordinary city traffic)",
                    ["category.traffic.desc"] = "私家车/出租车/货车动态改道",
                    ["category.citizens.title"] = "市民行为 (Citizens)",
                    ["category.citizens.desc"] = "依拥堵调整开车/出租车概率",
                    ["category.racecars.title"] = "赛车 (Race cars)",
                    ["category.racecars.desc"] = "速度上限、赛车场吸引力",
                    ["toggle.enable"] = "启用此功能 (Enable)",
                    ["toggle.on"] = "[开] ",
                    ["toggle.off"] = "[关] ",
                    ["button.scanTrain"] = "检测没有乘客的城际火车",
                    ["button.scanBus"] = "检测没有乘客的城际巴士",
                    ["category.intercityTrain.short"] = "城际火车 (intercity trains)",
                    ["category.intercityBus.short"] = "城际巴士 (intercity buses)",
                    ["scan.noneFound"] = "没有侦测到没有乘客的{0}。",
                    ["scan.confirm"] = "侦测到 {0} 辆没有乘客的{1}（共 {2} 节车厢/车辆实例）。\n\n是否要直接删除这些车辆？",
                    ["uui.tooltip"] = "AI_Improve 设定 (Settings)",
                    ["header.status"] = "运作中 (Active)",
                    ["header.changelog"] = "更新日志 (Changelog)",
                    ["header.search"] = "搜索设置",
                    ["header.reset"] = "重置为默认值",
                    ["header.reset.desc"] = "把所有功能开关和所有可调整数值还原成全新安装时的状态。你选择的语言不会被改动。",
                    ["header.reset.confirm"] = "要把 AI_Improve 的所有设置还原成默认值吗？\n\n这会影响所有功能开关和所有可调整数值。你选择的语言不会被改动。",
                    ["search.noResults"] = "找不到符合“{0}”的设置。清空搜索框即可回到分页列表。",
                    ["feature.rerouteTiming"] = "改道时机",
                    ["feature.rerouteTiming.desc"] = "所有改道功能共用的设置——这些控制的是车辆多常重新考虑路线，而不是要不要改道。",
                    ["tab.toggles"] = "功能开关",
                    ["tab.tuning"] = "数值调整",
                    ["tab.about"] = "关于",
                    ["about.version"] = "最后更新 (Updated) {0}",
                    ["about.github"] = "GitHub 源代码",
                    ["about.wiki"] = "说明 Wiki",
                    ["about.workshop"] = "Steam Workshop 页面",
                    ["about.reportIssue"] = "报告问题 (GitHub Issues)",
                    ["tune.fireResponders"] = "消防车/直升机每栋建筑派遣上限",
                    ["tune.fireResponders.desc"] = "同一栋燃烧中的建筑最多可以有几台消防车/直升机同时前往，超过的会被改派到其他地方。",
                    ["tune.lowRidership"] = "城际火车低载客量跳过阈值",
                    ["tune.lowRidership.desc"] = "最近载客量低于这个人数时，可能会跳过一次即将进站的城际火车，而不是让它几乎空车进站。设为 0 会完全停用这个节流机制。",
                    ["tune.verboseLogging"] = "详细记录 (只在报告问题时开启，会拖慢游戏)",
                    ["tune.verboseLogging.desc"] = "记录每一个派遣/改道/重新导向的细节，不只是摘要。只有在为了报告问题而重现时才需要开启，会大量写入硬盘。",
                    ["nav.general"] = "一般",
                    ["nav.citizens"] = "市民",
                    ["nav.emergency"] = "紧急服务",
                    ["nav.road"] = "道路交通",
                    ["nav.rail"] = "铁路",
                    ["nav.aviation"] = "航空",
                    ["nav.shipping"] = "船运与货运",
                    ["nav.races"] = "赛事",
                    ["nav.advanced"] = "进阶",
                    ["feature.fireResponseCap"] = "每栋建筑派遣上限",
                    ["feature.fireResponseCap.desc"] = "限制单一起火建筑最多可派遣多少消防车/直升机。",
                    ["feature.fireIdleSeek"] = "闲置车辆寻找附近火场",
                    ["feature.fireIdleSeek.desc"] = "闲置/返程中的消防车辆会优先检查附近是否还有火场。",
                    ["feature.helicopterWeatherHalt"] = "雷暴雨时停飞直升机",
                    ["feature.helicopterWeatherHalt.desc"] = "雷暴雨期间紧急直升机停留在地面。",
                    ["feature.metroPlatform"] = "站台分配",
                    ["feature.metroPlatform.desc"] = "依占用情况分配地铁站台。",
                    ["feature.metroReroute"] = "中途改道",
                    ["feature.metroReroute.desc"] = "地铁依实时拥堵情况改道。",
                    ["feature.trainPlatform"] = "站台分配",
                    ["feature.trainPlatform.desc"] = "依占用情况分配城际火车站台。",
                    ["feature.trainReroute"] = "中途改道",
                    ["feature.trainReroute.desc"] = "城际火车依实时拥堵情况改道。",
                    ["feature.trainSpawnThrottle"] = "入城流量节流",
                    ["feature.trainSpawnThrottle.desc"] = "当目的地饱和或载客量偏低时，节流新生成的城际火车。",
                    ["feature.singleTrackDetector"] = "单线轨道冲突侦测",
                    ["feature.singleTrackDetector.desc"] = "只侦测并记录，不会改变任何列车行为。",
                    ["feature.aircraftGate"] = "登机口分配",
                    ["feature.aircraftGate.desc"] = "依占用情况分配机场登机口。",
                    ["feature.aircraftReroute"] = "中途改道",
                    ["feature.aircraftReroute.desc"] = "飞机滑行时依实时拥堵情况改道。",
                    ["feature.aircraftThunderstorm"] = "雷暴雨拒绝起降",
                    ["feature.aircraftThunderstorm.desc"] = "雷暴雨期间机场拒绝起降。",
                    ["feature.localBusReroute"] = "市内巴士改道",
                    ["feature.localBusReroute.desc"] = "市内巴士依实时拥堵情况改道。",
                    ["feature.trafficReroute"] = "一般交通改道",
                    ["feature.trafficReroute.desc"] = "私家车/出租车/货车依实时拥堵情况改道。",
                    ["feature.helicopterGate"] = "客运直升机登机点分配",
                    ["feature.helicopterGate.desc"] = "依占用情况分配客运直升机登机点。",
                    ["feature.helicopterReroute"] = "客运直升机改道",
                    ["feature.helicopterReroute.desc"] = "客运直升机依实时拥堵情况改道。",
                    ["feature.helicopterCapacity"] = "客运直升机载客量提升",
                    ["feature.helicopterCapacity.desc"] = "提升客运直升机载客量。",
                    ["feature.intercityBusReroute"] = "城际巴士改道",
                    ["feature.intercityBusReroute.desc"] = "城际巴士依实时拥堵情况改道。",
                    ["feature.citizenCar"] = "依拥堵调整开车概率",
                    ["feature.citizenCar.desc"] = "市民较不倾向开车前往已拥堵的目的地。",
                    ["feature.citizenTaxi"] = "提升出租车使用率",
                    ["feature.citizenTaxi.desc"] = "提升出租车作为开车的替代选项。",
                    ["feature.raceAttractiveness"] = "赛车场吸引力提升",
                    ["feature.raceAttractiveness.desc"] = "提升赛车场综合设施的观光吸引力。",
                    ["feature.citizenTransportMode"] = "自定义交通方式权重",
                    ["feature.citizenTransportMode.desc"] = "取代原版的开车/出租车/自行车概率，改用 4 个你自定义的权重：步行、开车、出租车、大众运输。开启时会跳过上方的市民开车/出租车概率开关。",
                    ["feature.shipDock"] = "船运码头分配",
                    ["feature.shipDock.desc"] = "依占用情况分配货轮与客运渡轮的码头，把船运流量分散到港口真正的码头容量上，而不是挤在原版盲目挑中的同一个码头。",
                    ["tune.fireUncapMinutes"] = "燃烧几分钟后解除上限",
                    ["tune.fireUncapMinutes.desc"] = "一栋建筑燃烧超过这么久之后，派遣上限就不再套用在它身上——长时间的火灾会持续获得支援，不会卡在上限。",
                    ["tune.rerouteDensity"] = "改道拥堵阈值",
                    ["tune.rerouteDensity.desc"] = "前方道路/轨道/车道的拥堵度要达到多少（0-100）才会触发车辆行驶途中改道。数值越低，改道越积极。",
                    ["tune.stationSaturation"] = "车站饱和阈值",
                    ["tune.stationSaturation.desc"] = "当占用量最低的候选站台已经达到或超过这个值时，就视为该车站已饱和，改为保留原版自己的选择，不强制塞进还很拥挤的站台。",
                    ["tune.harborSaturation"] = "港口饱和阈值",
                    ["tune.harborSaturation.desc"] = "当占用量最低的候选码头已经达到或超过这个值时，就视为该港口已饱和，改为保留原版自己的选择，不强制塞进还很拥挤的码头。",
                    ["tune.dockCandidates"] = "码头搜索候选数",
                    ["tune.dockCandidates.desc"] = "在港口周围探测几个候选点来分散船只到各码头。数字越大覆盖范围越完整，但运算量也越高。",
                    ["tune.platformCandidates"] = "站台搜索候选数",
                    ["tune.platformCandidates.desc"] = "在车站周围探测几个候选点来分散火车到各站台。数字越大覆盖范围越完整，但运算量也越高。",
                    ["tune.lowRidershipSkipChance"] = "低载客量跳过概率 (%)",
                    ["tune.lowRidershipSkipChance.desc"] = "当车站低于低载客量阈值时，这是跳过一次进站火车而不是让它几乎空车抵达的概率百分比。",
                    ["tune.gateCandidates"] = "登机口搜索候选数",
                    ["tune.gateCandidates.desc"] = "在机场周围探测几个候选点来分散飞机到各登机口。数字越大覆盖范围越完整，但运算量也越高。",
                    ["tune.perGateCapacity"] = "每个登机口可容纳飞机数",
                    ["tune.perGateCapacity.desc"] = "机场找到的每个真实登机口大约可以容纳多少架飞机，超过就视为整个机场饱和（会依实际找到的登机口数量按比例调整）。",
                    ["tune.helicopterCapacity"] = "直升机载客量 (%)",
                    ["tune.helicopterCapacity.desc"] = "客运直升机座位容量，以载具原本容量的百分比表示（200 = 两倍）。",
                    ["tune.citizenCarDensity"] = "拥堵判定阈值",
                    ["tune.citizenCarDensity.desc"] = "目的地的拥堵度要达到多少（0-100）才会开始降低市民开车过去的概率。",
                    ["tune.citizenCarReduction"] = "最大概率降幅 (%)",
                    ["tune.citizenCarReduction.desc"] = "即使在最拥堵的情况下，拥堵最多可以降低市民开车概率的百分比上限。",
                    ["tune.taxiMultiplier"] = "出租车概率倍率 (%)",
                    ["tune.taxiMultiplier.desc"] = "把市民搭出租车的基础概率乘上这个倍率（150 = 1.5 倍）。",
                    ["tune.taxiFlatBonus"] = "出租车概率固定加成",
                    ["tune.taxiFlatBonus.desc"] = "在上面的倍率之外再加上的固定百分点加成，让出租车在基础概率接近零的情况下仍然是个实际选项。",
                    ["tune.raceAttractiveness"] = "吸引力倍率 (%)",
                    ["tune.raceAttractiveness.desc"] = "赛车场综合设施的观光吸引力，以原本数值的百分比表示（200 = 两倍）。",
                    ["tune.citizenWalkWeight"] = "步行权重",
                    ["tune.citizenWalkWeight.desc"] = "整趟行程都用走的的相对权重。0 = 没有市民会纯步行；数值越高越多人走路。跟下面另外 3 个权重相比较，不是绝对百分比。",
                    ["tune.citizenDriveWeight"] = "开车权重",
                    ["tune.citizenDriveWeight.desc"] = "开私家车的相对权重。跟另外 3 个权重相比较，不是绝对百分比。",
                    ["tune.citizenTaxiWeight"] = "出租车权重",
                    ["tune.citizenTaxiWeight.desc"] = "搭出租车的相对权重。跟另外 3 个权重相比较，不是绝对百分比。",
                    ["tune.citizenTransitWeight"] = "大众运输权重",
                    ["tune.citizenTransitWeight.desc"] = "允许搭乘大众运输的相对权重（巴士/地铁/火车/其他合并计算——原版没有办法单独指定某一种）。不是绝对保证：走到站牌仍然需要一些步行。",
                    ["preset.label"] = "快速套用模板",
                    ["preset.balanced"] = "均衡",
                    ["preset.transitOriented"] = "大众运输导向",
                    ["preset.carDependent"] = "汽车导向",
                    ["preset.walkable"] = "步行城市",
                    ["tune.rerouteCooldown"] = "改道冷却时间（秒）",
                    ["tune.rerouteCooldown.desc"] = "车辆改道后，至少要等这么久才能再次改道，避免在两条路线之间来回犹豫。",
                    ["tune.checkInterval"] = "检查间隔（帧数）",
                    ["tune.checkInterval.desc"] = "每隔几个模拟帧数重新检查一次每台车的拥堵状况。数值越大，运算量分散得越开，但对新拥堵的反应也越慢。",
                    ["lang.label"] = "语言 (Language)",
                },
            };

        public static string Get(string key)
        {
            string language = ResolveLanguage();

            if (Strings.TryGetValue(language, out Dictionary<string, string> table) &&
                table.TryGetValue(key, out string value))
            {
                return value;
            }

            return Strings[DefaultLanguage].TryGetValue(key, out string fallback) ? fallback : key;
        }

        public static string Get(string key, params object[] args) => string.Format(Get(key), args);

        // Every language code Localization actually has a translation table for - drives both
        // ResolveLanguage's override check and the language-cycle button in SettingsPageUI.cs, so
        // the two can't drift out of sync with each other.
        public static readonly string[] SupportedLanguages = { "en", "zh-tw", "zh-cn" };

        private static string ResolveLanguage()
        {
            string overrideLanguage = ModSettings.LanguageOverride.value;
            if (!string.IsNullOrEmpty(overrideLanguage) && overrideLanguage != "auto")
            {
                return overrideLanguage;
            }

            if (!LocaleManager.exists)
            {
                return DefaultLanguage;
            }

            string language = LocaleManager.instance.language;
            return string.IsNullOrEmpty(language) ? DefaultLanguage : language.ToLowerInvariant();
        }
    }
}
